Add instruction to update .bash_profile
extsoft/pem pull request #35
Opened 2017-05-22 12:58 UTC by AntonKarabaza

Modifications of .bash_profile during installing and uninstalling were removed.
Now there are suggestions how to update .bash_profile.

Affects 21

2017-05-22 14:04 UTC, extsoft requested changes
Also please review your commit message (at least you missed # before issue number).
Please ask me to review next time with "@extsoft" mention.

2017-05-22 14:04 UTC, extsoft commented on install.bash
> +    echo "  export PATH=$PEM_INSTALL_PATH/bin"':$PATH'
@AntonKarabaza Pass whole message into "". Remove spare single quotes.

2017-05-22 14:04 UTC, extsoft commented on install.bash
> +    echo "To allow pem command and pem completion add the following to your .bash_profile:"
@AntonKarabaza rewrite sentence in more easier format.

2017-05-22 14:28 UTC, AntonKarabaza commented on install.bash
> +    echo "  export PATH=$PEM_INSTALL_PATH/bin"':$PATH'
But it will expand the $PATH variable to output.

2017-05-22 14:45 UTC, extsoft commented on install.bash
> +    echo "  export PATH=$PEM_INSTALL_PATH/bin"':$PATH'
> But it will expand the $PATH variable to output.

What about escaping? `echo "\$PATH"`

2017-05-22 15:03 UTC, AntonKarabaza commented on install.bash
> +    echo "  export PATH=$PEM_INSTALL_PATH/bin"':$PATH'
> What about escaping? echo "\$PATH"

@extsoft Missed this, thank you.

2017-05-23 13:18 UTC, extsoft requested changes

2017-05-23 13:18 UTC, extsoft commented on install.bash
> +    echo "    [ -f $PEM_INSTALL_PATH/bin/pem-completion ] && . $PEM_INSTALL_PATH/bin/pem-completion"
@AntonKarabaza, the best way to add this instructions is to copy and paste. But in current implementation I can't do that:
1. Please add # before comments
2. Please make it in copy/paste format (remove extra spaces in the begging go the line

2017-05-24 10:25 UTC, closed without merging

2017-05-24 10:26 UTC, AntonKarabaza commented
@extsoft Pull request closed due to change of head branch.