Add documentation to 'python-remove'
extsoft/pem pull request #36
Opened 2017-05-23 13:34 UTC by ivan-podorozhnyi

Added 'python-remove' function description and usage line
Affects #30

2017-05-23 14:17 UTC, extsoft requested changes
@ivan-podorozhnyi thank you for contributing. Please fix comments.

2017-05-23 14:17 UTC, extsoft commented on bin/pem-python-remove
> +usage(){
@ivan-podorozhnyi Please order messages as described in task.

2017-05-23 14:17 UTC, extsoft commented on bin/pem-python-remove
> +    echo "Usage: pem python-remove <version>"
@ivan-podorozhnyi add empty line after this message.

2017-05-23 14:17 UTC, extsoft commented on bin/pem-python-remove
> +    [ "$1" = "-h" ] && usage && exit 0
@ivan-podorozhnyi don't do this. Please take a look for https://github.com/extsoft/pem/commit/90f87066d1a54814ea5134bd37429baa96555b83

2017-05-23 14:41 UTC, ivan-podorozhnyi commented
Ok, I will make changes accordingly

2017-05-25 09:33 UTC, extsoft approved these changes
@ivan-podorozhnyi thanks!

2017-05-25 09:34 UTC, merged