Print help when run 'pem' with a command
extsoft/pem pull request #39
Opened 2017-05-24 09:14 UTC by ivan-podorozhnyi

Issue fixed, now result is the same as 'pem help'
Affects #37

2017-05-25 10:01 UTC, extsoft requested changes
@ivan-podorozhnyi , Take a look for debug output:
```
~/pem/bin export PEM_DEBUG=yes
~/pem/bin ./pem
++ dirname ./pem
+ PEM_DIR=.
+ main
+ local COMMAND=
+ shift
```

2017-05-25 10:01 UTC, extsoft commented on bin/pem
> +    [ ! -e "$PEM_DIR/pem-$COMMAND" -o -z "$COMMAND" ] && echo "Unknown command: pem $COMMAND" && usage && exit 2
@ivan-podorozhnyi 

1. The issue is still reproducible. 
2. When call `pem`, we have to see `usage` output only.

2017-05-26 08:07 UTC, ivan-podorozhnyi commented
@extsoft please check updates. Seems now its working correctly

2017-05-26 12:58 UTC, extsoft approved these changes
@ivan-podorozhnyi good job!

2017-05-26 12:58 UTC, extsoft commented on bin/pem
> +    if [ "$1" != "" ]; then
@ivan-podorozhnyi use `-z` to check is var empty or not next time.

2017-05-26 12:58 UTC, merged