Fix output of 'pem python-install help' command
extsoft/pem pull request #49
Opened 2017-05-29 07:52 UTC by ivan-podorozhnyi

Issue fixed. 'pem python-install help' command works properly.
Affects #48

2017-05-29 11:33 UTC, extsoft requested changes
@ivan-podorozhnyi please rewrite commit message.

2017-05-29 11:38 UTC, ivan-podorozhnyi commented
@extsoft done

2017-06-01 12:55 UTC, extsoft requested changes

2017-06-01 12:55 UTC, extsoft commented on tests/pem-python-install-help.bats
> +
@ivan-podorozhnyi, you forget to connect commons.

2017-06-02 07:40 UTC, extsoft approved these changes

2017-06-02 07:40 UTC, merged

2017-06-02 07:40 UTC, extsoft commented
@ivan-podorozhnyi merged.